### ISSUE TITLE
Moving between fields in eplot-controls

### ISSUE THREAD

**Issue by nemethf** [larsmagne/eplot#11]
What is the recommended way to move between input fields in the eplot-controls buffer?  I use `C-n`, `C-p`, `M-f`, `M-b`, `TAB`, but it's kind of cumbersome.  Would it be possible to jump to the next / previous field with, say, `C-<tab>` / `<backtab>`?

(eplot-control-next-input does not jump to the next input when the point is in an input field and there is no eplot-control-previous-input.)

Thank you.

**Comment by larsmagne** [comment]
Yeah, I guess C-<tab> / <backtab> would make sense to move between input fields, but I wasn't sure whether it would be worthwhile to add them.  Using the cursor keys would usually be faster, I think.

**Comment by larsmagne** [comment]
I've now implemented this.
