### ISSUE TITLE
Date labels?

### ISSUE THREAD

**Issue by unhammer** [larsmagne/eplot#12]
I see I can plot things like number of times the machine caught fire per date with

```
Data-Format: date
Format: bar-chart

20240726 1
20240727 1
20240731 1
20240516 2
20240708 2
20240611 3
20240701 4
20240624 5
20240728 6
20240712 37
```
but I don't get any date labels. Is it possible to get something like

![bilde](https://github.com/user-attachments/assets/08245788-cd34-4f34-8a2c-68643754c68e)

?

**Comment by larsmagne** [comment]
bar charts are for, well, displaying bars of different heights, so it doesn't make sense to combine them with dates.

To achieve the plot kinda like what your screenshot looks like, say something like:

Data-Format: date
Style: circle
Fill-Color: blue

This makes all circles the same size, though, and in your has different sizes -- depending on the value?  You can get that by:

Data-Format: date
Style: circle
Fill-Color: blue

20240726 1
20240727 1
20240731 1
20240516 2 # Size: 6
20240708 2 # Size: 6
20240611 3 # Size: 9
20240701 4 # Size: 12
20240624 5 # Size: 15
20240728 6 # Size: 18
20240712 37 # Size: 111

But perhaps it would be nice to have a circle style that also automatically sizes the circle based on the values?  Hm, yes, I think I'll add that.

**Comment by larsmagne** [comment]
I've now implemented this with the Size-Factor option.

**Comment by unhammer** [comment]
That Size-Factor is pretty nice, thanks :-) but what I was really asking about was the X labels, for some reason I didn't see them when I first tried this, but now (running 5c184f8d4e723ba42a030b22819fe0e54059d20c ) I do, not sure what I did wrong first. Now I get 

![bilde](https://github.com/user-attachments/assets/79e83719-3e8e-4086-86a4-242a4c7cbc2d)

which at least shows them. But it would be nice if there were a way to format those dates, maybe `X-Label-Date-Format: %b %d` could override the default format-time-string for dates in eplot--format-value and give 

![bilde](https://github.com/user-attachments/assets/17b1c97b-20b1-49f9-b885-a613e84da3a4)

**Comment by larsmagne** [comment]
There's already X-Label-Format, so we could extend that to do format-time-string on date charts...

OK, done:

X-Label-Format: %b %e

Hm, %e is annoyingly space-padded in the front...  Oh, that doesn't make a difference for SVG -- it seems to disregard multiple spaces here.
