### ISSUE TITLE
Great package!

### ISSUE THREAD

**Issue by OrionRandD** [larsmagne/eplot#2]
Great package!
Could you just, if possible, to write a Readme.md showing how to install it on Emacs?
And also submitting it to MELPA for them to see if they approve it to be in the MELPA repository?

**Comment by s-kostyaev** [comment]
Or even submit it to GNU ELPA

**Comment by larsmagne** [comment]
I've now added some instructions to the readme file.

As for an ELPA, I guess it'll land there after it's finished, but it's still a work in progress.
