### ISSUE TITLE
multiple data series

### ISSUE THREAD

**Issue by hajovonta** [larsmagne/eplot#7]
Is there a possibility to draw multiple series on a single chart, from different data sources perhaps? I couldn't find any examples for this besides the in-between filling which is not exactly what I want.

**Comment by larsmagne** [comment]
Yes, you can do something like:

Layout: compact
Width: 300
Height: 200

Data-File: data1.txt

Style: impulse
Color: blue
Data-File: data2.txt

**Comment by unhammer** [comment]
I see https://github.com/larsmagne/eplot/blob/main/examples/chart-two-plots.plt works, but I can't get this to work with time series, where things have to match up on column 1. If I do

```plt
Data-Format: date
Data-Column: 1
Size: 3
Style: impulse
Color: blue
20260107	4323	2920
20260115	2413	1505
20260116	5082	1604
```
I can switch data-column between 1 and 2 to get different charts. But if I do

```sh
$ cut -f1,2 both.tsv >2.tsv
$ cut -f1,3 both.tsv >3.tsv
```
and

```plt
Data-Format: date
Size: 3
Style: impulse
Color: blue
Data-File: 2.tsv

Data-Format: date
Size: 3
Style: impulse
Color: red
Data-File: 3.tsv
```

then it seems to only show data from 3.tsv, in blue. What am I doing wrong? Is it possible to get it to join data on column 1?

**Comment by unhammer** [comment]
Oh this is weird, if I add a blank line to the top of the file, it works!

Also, prepending

```plt
Layout: compact
Width: 500
Height: 500

```

works, as long as there is a blank line before the section belonging to data-file 2. It seems blank lines are important?
